"""relationship added between modules and assessments

Revision ID: 1aa80641d622
Revises: 
Create Date: 2021-12-08 03:06:44.890070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa80641d622'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('module_code', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('num_of_assessments', sa.Integer(), nullable=True),
    sa.Column('average', sa.Integer(), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('module_code')
    )
    op.create_index(op.f('ix_modules_title'), 'modules', ['title'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('username', sa.String(length=1000), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_username'), 'students', ['username'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('worth', sa.Integer(), nullable=True),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.Column('module_code', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['module_code'], ['modules.module_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_title'), 'assessments', ['title'], unique=False)
    op.create_table('enrollment',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('module_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_code'], ['modules.module_code'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_assessments_title'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_students_username'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_modules_title'), table_name='modules')
    op.drop_table('modules')
    # ### end Alembic commands ###
