"""initial migration

Revision ID: 2fd095c423ef
Revises: 
Create Date: 2021-12-13 17:51:15.733511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd095c423ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('username', sa.String(length=1000), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_username'), ['username'], unique=True)

    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_code', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('num_of_assessments', sa.Integer(), nullable=True),
    sa.Column('completed_assessments', sa.Integer(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('weighted_average', sa.Float(), nullable=True),
    sa.Column('percent_completed', sa.Float(), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modules_title'), ['title'], unique=False)

    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('score_percent', sa.Float(), nullable=True),
    sa.Column('assessment_worth', sa.Integer(), nullable=True),
    sa.Column('module_code', sa.String(length=1000), nullable=True),
    sa.Column('student_id', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['module_code'], ['modules.module_code'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_title'), ['title'], unique=False)

    op.create_table('enrollment',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('module_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_code'], ['modules.module_code'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_title'))

    op.drop_table('assessments')
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modules_title'))

    op.drop_table('modules')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_username'))

    op.drop_table('students')
    # ### end Alembic commands ###
