"""updated student username to be unique

Revision ID: 502e326a1416
Revises: 28ba2fc7a0c9
Create Date: 2021-12-10 07:31:35.653002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502e326a1416'
down_revision = '28ba2fc7a0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index('ix_students_username')
        batch_op.create_index(batch_op.f('ix_students_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_username'))
        batch_op.create_index('ix_students_username', ['username'], unique=False)

    # ### end Alembic commands ###
